version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: SuperStrongPassword

  generation:
    build: ./generation
    restart: always
    depends_on:
      - persistence

  persistence:
    build: ./persistence
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db

  rest-api:
    build: ./rest-api
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - persistence

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - rest-api
